var a = String(2);
var b = Number("2");
var c = Boolean(0);
var d = Boolean(1);
var e = Boolean(-1);
var f = Boolean("hola");
console.log (g);
console.log (h);
console.log(c);
console.log(d);
console.log(e);
console.log(f);
